language: csharp
solution: pong.sln
install:
  - nuget restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release pong.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./pong.Tests/bin/Release/pong.Tests.dll
